# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/skill.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/skill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/skill.proto\x12\tai_engine\"Q\n\x11ListSkillsRequest\x12\x11\n\x04type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x65nabled\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x07\n\x05_typeB\n\n\x08_enabled\"\xda\x01\n\tSkillInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nmodel_name\x18\x05 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x06 \x01(\x08\x12\x38\n\nparameters\x18\x07 \x03(\x0b\x32$.ai_engine.SkillInfo.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\":\n\x12ListSkillsResponse\x12$\n\x06skills\x18\x01 \x03(\x0b\x32\x14.ai_engine.SkillInfo2Y\n\x0cSkillService\x12I\n\nListSkills\x12\x1c.ai_engine.ListSkillsRequest\x1a\x1d.ai_engine.ListSkillsResponseB\x1a\n\x16\x63om.xxx.ai.engine.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.skill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.xxx.ai.engine.grpcP\001'
  _globals['_SKILLINFO_PARAMETERSENTRY']._loaded_options = None
  _globals['_SKILLINFO_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_LISTSKILLSREQUEST']._serialized_start=33
  _globals['_LISTSKILLSREQUEST']._serialized_end=114
  _globals['_SKILLINFO']._serialized_start=117
  _globals['_SKILLINFO']._serialized_end=335
  _globals['_SKILLINFO_PARAMETERSENTRY']._serialized_start=286
  _globals['_SKILLINFO_PARAMETERSENTRY']._serialized_end=335
  _globals['_LISTSKILLSRESPONSE']._serialized_start=337
  _globals['_LISTSKILLSRESPONSE']._serialized_end=395
  _globals['_SKILLSERVICE']._serialized_start=397
  _globals['_SKILLSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
