# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.ts_scripts import skill_pb2 as protos_dot_skill__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/skill_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkillServiceStub(object):
    """技能服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSkills = channel.unary_unary(
                '/ai_engine.SkillService/ListSkills',
                request_serializer=protos_dot_skill__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=protos_dot_skill__pb2.ListSkillsResponse.FromString,
                _registered_method=True)


class SkillServiceServicer(object):
    """技能服务
    """

    def ListSkills(self, request, context):
        """列出所有可用的技能
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=protos_dot_skill__pb2.ListSkillsRequest.FromString,
                    response_serializer=protos_dot_skill__pb2.ListSkillsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_engine.SkillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_engine.SkillService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkillService(object):
    """技能服务
    """

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.SkillService/ListSkills',
            protos_dot_skill__pb2.ListSkillsRequest.SerializeToString,
            protos_dot_skill__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
